# Project information
site_name: Currículo Profissional
#site_url: http://arrs82.github.io/
site_author: Alessandro Roberto dos Reis Santos
site_description: >-
  Currículo Profissional

# Repository
#repo_name: arrs82.github.io
#repo_url: https://github.com/arrs82/curriculo
#edit_uri: edit/main/docs
#edit_uri_template: 'blob/main/docs/{path}'

# Copyright
copyright: © 2025 Curriculo Profissional - Alessandro Roberto dos Reis Santos

# Page tree
nav:
        - Apresentação Pessoal: index.md
        - Dados Pessoais: dados-pessoais.md
        - Objetivos Profissionais: objetivos.md
        - Formação Acadêmica: formacao-academica.md
        - Cursos Extracurriculares: cursos-extracurriculares.md
        - Informática: informatica.md
        - Língua Estrangeira: lingua-estrangeira.md
        - Experiência Profissional: experiencia-profissional.md
        - Seminários Motivacionais: seminarios-motivacionais.md
        - Portfólio de Criação: portfolio-criacao.md
        #- Projetos de Infraestrutura: projetos-infra.md
                # - Proxmox: projetos-infra/proxmox.md
                # - Pfsense Firewall: projetos-infra/pfsense-firewall.md
                # - Plex Media Server: projetos-infra/plex-media-server.md
                # - Material for Mkdocs: projetos-infra/material-mkdocs.md
                # - Linux (Comandos): projetos-infra/linux-comandos.md
                # - Tutoriais Diversos: projetos-infra/tutoriais-diversos.md
        - Conteúdo Pessoal: conteudo-pessoal.md
        - Sobre: sobre.md
        #- Documentos Pessoais: documentos-pessoais.md
        #- Ícones e Utilitários: icones.md

# Configuration
theme:
        name: material
        custom_dir: overrides
        language: pt-BR
        icon:
                logo: fontawesome/solid/user-tie
        logo: assets/images/logo-curriculo.png
        favicon: assets/images/favicons/favicon.ico
        features:
                - announce.dismiss
                # - content.action.edit
                # - content.action.view
                - content.code.annotate
                - content.code.copy
                - content.tabs.link
                - content.tooltips
                # - header.autohide # Faz o cabeçalho superior se esconder ao rolar
                # - navigation.expand
                - navigation.footer
                # - navigation.indexes
                - navigation.instant
                # - navigation.prune
                - navigation.sections
                # - navigation.tabs
                - navigation.tabs.sticky # Congela as abas de navegação
                - navigation.top
                - navigation.tracking
                - search.highlight
                - search.share
                - search.suggest
                - toc.follow
                # - toc.integrate
        palette:
                - scheme: default
                  primary: blue grey
                  accent: indigo
                  toggle:
                    icon: material/toggle-switch
                    name: Switch to dark mode
                - scheme: slate
                  primary: blue grey
                  accent: indigo
                  toggle:
                    icon: material/toggle-switch-off-outline
                    name: Switch to light mode
        font:
                text: Roboto
                code: Roboto Mono

# Customization
extra:
        analytics:
                provider: google
                property: G-GCRKKC1EG7
        social:
                - icon: fontawesome/brands/instagram
                  link: https://www.instagram.com/aleha.santos/
                - icon: fontawesome/brands/facebook
                  link: https://facebook.com/aleha.santos82
                - icon: fontawesome/brands/youtube
                  link: https://www.youtube.com/@aleha.santos
                - icon: fontawesome/brands/linkedin
                  link: https://www.linkedin.com/in/alessandroroberto82
                - icon: fontawesome/brands/x-twitter
                  link: https://x.com/aleha_santos
                #- icon: fontawesome/brands/github
                #  link: https://github.com/arrs82
                - icon: fontawesome/brands/whatsapp
                  link: https://wa.me/5512988678750

        caption: true
        lazy_load: true
        align: center
        generator: false

# CSS e Javascript
extra_css:
    - 'assets/css/extra.css'
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
    - assets/javascripts/highlight.js
    - assets/javascripts/ipinfo.js
    - assets/javascripts/iplogger.js

# Plugins
plugins:
        - search:
                lang: pt
        - minify:
                minify_html: true
        - git-revision-date-localized:
                # enabled: !ENV [CI, false]
                enable_creation_date: true
                fallback_to_build_date: false
                type: timeago
                locale: 'pt'  # Certifique-se de que este é um código de 2 letras válido

# Extensions
markdown_extensions:
        - abbr
        - admonition
        - attr_list
        - def_list
        - pymdownx.tasklist:
                custom_checkbox: true
        - footnotes
        - md_in_html
        #- toc:
        #        permalink: true
        - pymdownx.arithmatex:
                generic: true
        - pymdownx.betterem:
                smart_enable: all
        - pymdownx.caret
        - pymdownx.details
        - pymdownx.emoji:
                emoji_index: !!python/name:material.extensions.emoji.twemoji
                emoji_generator: !!python/name:material.extensions.emoji.to_svg
                options:
                  custom_icons:
                    - overrides/.icons
        - pymdownx.highlight:
                anchor_linenums: true
                line_spans: __span
                pygments_lang_class: true
        - pymdownx.inlinehilite
        - pymdownx.snippets
        - pymdownx.keys
        - pymdownx.magiclink:
                repo_url_shorthand: true
                user: arrs82
                repo: mkdocs-material-template
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences:
                custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_code_format
                - name: python  # Exemplo para outras linguagens
                  class: python
                  format: !!python/name:pymdownx.superfences.fence_code_format
                - name: "*"
                  class: "highlight"
                  format: !!python/name:pymdownx.superfences.fence_code_format
        - pymdownx.tabbed:
                alternate_style: true
        - pymdownx.inlinehilite  # Para código inline
        - pymdownx.tasklist:
                custom_checkbox: true
        - pymdownx.tilde